## Loading data into Pandas

In [19]:
import pandas as pd

# data = pd.read_csv('pokemon_data.csv')

# df = pd.DataFrame(data)

# df.head(5)
# df.tail(5)

# df_xlsx = pd.read_excel('pokemon_data.xlsx')
# df_xlsx = pd.read_excel('pokemon_data.xlsx', sheet_name='Sheet2')
# print(df_xlsx.head())

# df = pd.read_csv('pokemon_data.txt', delimiter='\t')
# # df = pd.read_csv('pokemon_data.txt')

# print(df.head(5))

# df['Name']
# df[['HP','Name']]

df_json= pd.read_json('pokemon_data.json')
df_json['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

## Reading Data in Pandas

In [50]:
#### Read Headers
# df.columns

## Read each Column
# df[['Name', 'Type 1', 'HP']]

## Read Each Row
# print(df.iloc[0:4])
# df.head(4)

# a = ['apple','banana', 'mango']
# for i, r in enumerate(a):
#     print(i," : ", r)

# for index, row in df.iterrows():
#     print(index, row['Name'])

# df.loc[df['Type 1'] == "Grass" ]
# df.loc[(df['Type 1'] == "Grass") | (df['HP'] == 45) & (df['Defense'] > 60)] # not proper output 
# df.loc[((df['Type 1'] == "Grass") | (df['HP'] == 45)) & (df['Defense'] > 60)]
# df
#Read a specific location (R,C)
# print(df.iloc[2,1])
# print(df.head(5))
# df['Name'][2]

Venusaur
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

'Venusaur'

## Sorting/Describing Data

In [60]:
# df.sort_values(['Name','Type 1', 'HP'], ascending=False)

# df.sort_values(['Name','Type 1', 'HP'], ascending=[0,1,1])

# df.shape # to know exact rows and columns in the dataset

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

## Making changes to the data

In [106]:
 # df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

# df = df.drop(columns=['Total'])

# df['Total'] = df.iloc[:, 4:10].sum(axis=1)
# df
# df.columns
# cols = list(df.columns)


# df = df[cols[0:4] + [cols[-1]]+cols[4:12]]
# df
dff= df[['Sp. Atk', 'Sp. Def', 'Speed','HP','Defense','Attack'] ]
print(dff)
print(df)
# df.head(5)

     Sp. Atk  Sp. Def  Speed  HP  Defense  Attack
0         65       65     45  45       49      49
1         80       80     60  60       63      62
2        100      100     80  80       83      82
3        122      120     80  80      123     100
4         60       50     65  39       43      52
..       ...      ...    ...  ..      ...     ...
795      100      150     50  50      150     100
796      160      110    110  50      110     160
797      150      130     70  80       60     110
798      170      130     80  80       60     160
799      130       90     70  80      120     110

[800 rows x 6 columns]
       #                   Name   Type 1  Type 2  Generation  Legendary  \
0      1              Bulbasaur    Grass  Poison           1      False
1      2                Ivysaur    Grass  Poison           1      False
2      3               Venusaur    Grass  Poison           1      False
3      3  VenusaurMega Venusaur    Grass  Poison           1      False
4      4             Charmander     Fire     NaN           1      False
..   ...                    ...      ...     ...         ...        ...
795  719                Diancie     Rock   Fairy           6       True
796  719    DiancieMega Diancie     Rock   Fairy           6       True
797  720    HoopaHoopa Confined  Psychic   Ghost           6       True
798  720     HoopaHoopa Unbound  Psychic    Dark           6       True
799  721              Volcanion     Fire   Water           6       True

     Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0     1683  45      49       49       65       65     45
1     2130  60      62       63       80       80     60
2     2750  80      82       83      100      100     80
3     3350  80     100      123      122      120     80
4     1529  39      52       43       60       50     65
..     ...  ..     ...      ...      ...      ...    ...
795   3350  50     100      150      100      150     50
796   3650  50     160      110      160      110    110
797   3250  80     110       60      150      130     70
798   3680  80     160       60      170      130     80
799   3250  80     110      120      130       90     70

[800 rows x 13 columns]

In [58]:
45+49+49+65+65+45

318

## Saving our Data (Exporting into Desired Format)

In [116]:
# dff.to_csv('hp_to_speed.csv', index=False)
# df.to_csv('modified.csv', index=False)

# # dff.to_excel('modifieddata.xlsx', index=False)

# dff.to_csv('modified.txt', index=False, sep='\t')
dff.to_json('modifiedjson.json')